### PR TITLE
257 2

### PR DESCRIPTION
**Pull request by marscher**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marscher** [comment]
@conda-forge-admin please rerender

**Comment by marscher** [comment]
@clonker for python-3.8 I guess we need to rebuild thermotools, msmtools and bhmm as well (prior this PR gets mergeable). Or would you prefer to skip the build for this Python version and stick more to scikit-time?

**Comment by clonker** [comment]
No you are right. It should be a matter of increasing the build number and rerendering right? If so I am going to prepare pull requests.

**Comment by clonker** [comment]
Actually I think for bhmm it would make sense to have a patch release even to include the RNG reseeding fix.

**Comment by marscher** [comment]
@conda-forge-admin please rerender

**Comment by marscher** [comment]
thanks @clonker for fixing all the perquisites

**Pull request merged**
